version: '3'

services:
  app:
    image: nextcloud:27.1.2-apache
    restart: unless-stopped
    networks:
      - web
    volumes:
      - ${HM_DATA_DIR}/main:/var/www/html
      - ${HM_DATA_DIR}/data:/var/www/html/data
      - ${HM_DATA_DIR}/apps2:/var/www/html/custom_apps
      - ${HM_DATA_DIR}/config:/var/www/html/config
      - ./apache-sites-default.conf:/etc/apache2/sites-enabled/000-default.conf:ro
#      - ./apache-sites-ssl.conf:/etc/apache2/sites-enabled/001-ssl.conf:ro
      - ./apache-conf-prefork.conf:/etc/apache2/conf-enabled/prefork.conf:ro
#      - ./apache-modules-ssl.conf:/etc/apache2/mods-enabled/ssl.conf:ro
#      - ./apache-modules-ssl.load:/etc/apache2/mods-enabled/ssl.load:ro
      - ./apache-modules-socache_shmcb.load:/etc/apache2/mods-enabled/socache_shmcb.load:ro
      - ${HM_CACHE_DIR}/logs/apache_access.log:/var/log/apache2/access.log
      - ${HM_CACHE_DIR}/logs/apache_error.log:/var/log/apache2/error.log
      - ${HM_CACHE_DIR}/logs/apache_other_vhosts_access.log:/var/log/apache2/other_vhosts_access.log
      - ${HM_CACHE_DIR}/logs/nextcloud.log:/var/www/html/data/nextcloud.log

networks:
  web:
    external: true
