version: '3'

services:
  nginx:
    image: nginx:1.21.5-alpine
    restart: unless-stopped
    networks:
      - web
    ports:
      - 80:80/tcp
      - 443:443/tcp
    volumes:
      - ./conf.d:/etc/nginx/conf.d:ro
      - ${HM_DATA_DIR}/dhparam.pem:/etc/nginx/ssl/dhparam.pem:ro
      - /opt/certbot-data/letsencrypt/archive/muflone.com/privkey1.pem:/etc/nginx/ssl/privkey.pem:ro
      - /opt/certbot-data/letsencrypt/archive/muflone.com/cert1.pem:/etc/nginx/ssl/cert.pem:ro
      - /opt/certbot-data/letsencrypt/archive/muflone.com/chain1.pem:/etc/nginx/ssl/chain.pem:ro
      - /opt/certbot-data/letsencrypt/archive/muflone.com/fullchain1.pem:/etc/nginx/ssl/fullchain.pem:ro
      - /opt/nginx-data/default:/var/www/default:ro
      - /opt/nginx-data/muflone.com:/var/www/muflone.com:ro
      - /opt/nginx-data/repositories.muflone.com:/var/www/repositories.muflone.com:ro
      - /opt/nginx-data/vbsimple.net:/var/www/vbsimple.net:ro
      - ${HM_CACHE_DIR}/logs:/var/log/nginx:rw

networks:
  web:
    external: true
