apps:
  hello_world:
    url: https://github.com/muflone/harbormaster-cloud7.git
    branch: main
    compose_config:
      - apps/hello_world/docker-compose.yaml

  portainer:
    url: https://github.com/muflone/harbormaster-cloud7.git
    branch: main
    enabled: false
    compose_config:
      - apps/portainer/docker-compose.yaml
