apps:
  hello_world:
    url: https://github.com/muflone/harbormaster-cloud7.git
    branch: main
    enabled: true
    compose_config:
      - apps/hello_world/docker-compose.yaml

  portainer_agent:
    url: https://github.com/muflone/harbormaster-cloud7.git
    branch: main
    enabled: false
    compose_config:
      - apps/portainer_agent/docker-compose.yaml

  certbot:
    url: https://github.com/muflone/harbormaster-cloud7.git
    branch: main
    enabled: false
    compose_config:
      - apps/certbot/docker-compose.yaml

  nginx:
    url: https://github.com/muflone/harbormaster-cloud7.git
    branch: main
    enabled: true
    compose_config:
      - apps/nginx/docker-compose.yaml

  mysql:
    url: https://github.com/muflone/harbormaster-cloud7.git
    branch: main
    enabled: true
    compose_config:
      - apps/mysql/docker-compose.yaml

  pastey:
    url: https://github.com/muflone/harbormaster-cloud7.git
    branch: main
    enabled: true
    compose_config:
      - apps/pastey/docker-compose.yaml

  yourls:
    url: https://github.com/muflone/harbormaster-cloud7.git
    branch: main
    enabled: true
    compose_config:
      - apps/yourls/docker-compose.yaml
